# Kira Novitchkova-Burbank

# Section 2: Sparse Matrices, Symmetric Matrices, and Relations/Graphs

In this section we will investigate matrices with special structure and work with our first matrix applications.

In data science and generally matrices can be thought of as a relationship between the columns and the rows. The value in the matrix describes how its column relates to its row. Another math construction for describing relationships is the graph. This makes matrices a powerful representation when working with graph information.

Recall that a graph is a collection of vertices (or nodes) and edges between the vertices. Both the vertices and edges can contain metadata. There are many variations on graphs but for our purpose we will stick to a few rules:
*   Edges must connect two different vertices or create a loop on a single vertex
*   Edges are bidirectional (undirected graph)


## Graph Example

We could create a graph of students at the PSU representing the relationship of having a class together. Students are the vertices. Edges show if two students are in the same class.

We could add even more information to the edges, like the number of classes the students together. Each student would have a self loop edge with the number of classes they are enrolled in.

This example generates a *symmetric* relationship. Justify to yourself why.

## Matrix Representation

Let's see if we can convert this relationship to a matrix. Below I have made a small dataset with students to work with.

If you aren't familiar with python, this is a `dict` (dictionary). A `dict` is a key-value store that allows you to look up values when providing a key. Here the keys are `string`s of students names and the values are `int`s (class IDs). A `dict` cannot have duplicate keys and will overwrite data with multiple assignments.

In [ ]:
import numpy as np
#ordered, changeable, and duplicates are not allowed
data = {
    'alice':[0,1,6], #key:value (list of numbers)  student:class id
    'bob':[2,7],
    'jack':[2,4,5,1],
    'suzie':[0,5,2],
    'chad':[1,3],
    'karen':[3,6]
    }

We stated that matrices are relations. I can think of a few different relationships from this dataset but let's start with the simplest, student-class. Let's figure out the dimension of this matrix and give the students an enumerated ID.

In [ ]:

student_ids = dict()
id_counter = 0
class_ids_set = set()

#6x8 matrix 6 students 8 classes      which student has which classes
for student, class_list in data.items(): #chose whatever names you want for names and values
  if student not in student_ids:
    student_ids[student] = id_counter
    id_counter += 1


  # using a `dict` with only keys and no values makes it a `set`

  #Note about sets:
  #A set does not hold duplicate items
  #The elements of the set are immutable, that is, they cannot be changed, but the set itself is mutable, that is, it can be changed
  #Since set items are not indexed, sets don't support any slicing or indexing operations.
  class_ids_set.update(class_list)


print(f'student count: {id_counter}')
print('student IDs:')
print(student_ids)
print('class IDs:')
print(class_ids_set)
class_count = len(class_ids_set)

print(f'\nclass count: {class_count}')
print(f'id_counter: {id_counter}')



student count: 6
student IDs:
{'alice': 0, 'bob': 1, 'jack': 2, 'suzie': 3, 'chad': 4, 'karen': 5}
class IDs:
{0, 1, 2, 3, 4, 5, 6, 7}

class count: 8
id_counter: 6


We find that our data has 6 students and 8 unique classes.

That means our resulting student to class relationship matrix has dimension of (6, 8).

## Exercise 2.1

Implement the function below that creates this matrix from the student-class data, student IDs, and shape.

Add the data 1.0 into the matrix below where appropriate.

In [ ]:
def student_class_matrix(data: dict, student_ids: dict, shape: tuple) -> np.array:
  matrix = np.zeros(shape)
  #pass in (6,8)


  for name, classes in data.items():
    id = student_ids[name]
    print(f'name: {name} id: {id}')
    print(classes)
    for class_id in classes:
      matrix[id,class_id] = 1
  return matrix

A = student_class_matrix(data, student_ids, (id_counter, class_count))
A

name: alice id: 0
[0, 1, 6]
name: bob id: 1
[2, 7]
name: jack id: 2
[2, 4, 5, 1]
name: suzie id: 3
[0, 5, 2]
name: chad id: 4
[1, 3]
name: karen id: 5
[3, 6]


array([[1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0.]])

Now that we have the matrix form of the student-class relationship, let's see what happens when we take $AA^T$ or $A^TA$.

In [ ]:
A @ A.T #6x6matrix       studentxstudent

array([[3., 0., 1., 1., 1., 1.],
       [0., 2., 1., 1., 0., 0.],
       [1., 1., 4., 2., 1., 0.],
       [1., 1., 2., 3., 0., 0.],
       [1., 0., 1., 0., 2., 1.],
       [1., 0., 0., 0., 1., 2.]])

In [ ]:
A.T @ A #8x8matrix      classxclass

array([[2., 1., 1., 0., 0., 1., 1., 0.],
       [1., 3., 1., 1., 1., 1., 1., 0.],
       [1., 1., 3., 0., 1., 2., 0., 1.],
       [0., 1., 0., 2., 0., 0., 1., 0.],
       [0., 1., 1., 0., 1., 1., 0., 0.],
       [1., 1., 2., 0., 1., 2., 0., 0.],
       [1., 1., 0., 1., 0., 0., 2., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

## Exercise 2.2

Use this text box to describe in a few sentences the relationship these matrices describe.

Hint 1: notice the dimension of the resulting matrices.

Hint 2: both of these matrices are *adjacency* matrices as discussed in lecture.

### Response here:

A @ A.T is a 6x6 matrix. It is a combination of 6x8 and 8x6 matrices.
It is a studentxstudent matrix that shows which students have classes together. It is symmetric. The numbers on the diagonal show how many classes each student has. For example: a00 is a student that has 3 classes.


A.T @ A is a 8x8 matrix. It is a combination of 8x6 and 6x8 matrices.       It is a classxclass matrix that shows which students share the same classes.
It is symmetric. Along the diagonal it shows how many students in a class and others are overlapping students.

## Sparsity

The three relationship matrices we just generated have a lot of zeros in them. When working with larger sparse datasets, these zeros can be left out to save on memory and algorithm complexity. The three main formats for storing sparse matrices are:
*   `coo` --- coordinate or triplet form
*   `csr` --- compressed sparse row
*   `csc` --- compressed sparse column

but there are also others. Check out the list of [sparse matrix classes](https://docs.scipy.org/doc/scipy/reference/sparse.html) provided by `scipy`.

In lecture, you have talked about the formal description of the three main formats. Note that `scipy`'s specification is slightly different than what you learned in class! At the [bottom of the usage page](https://docs.scipy.org/doc/scipy/reference/sparse.html#further-details) we see:
> CSR column indices are not necessarily sorted. Likewise for CSC row indices. Use the .sorted_indices() and .sort_indices() methods when sorted indices are required

Keep in mind that not all specifications and implementations are the same and reading the specification is the only solution.

## Exercise 2.3

Implement the functions below that convert between dense and sparse formats. Use the matrices from the student-student and student-class relations to check your implementation.

Hint: in the sparse to dense functions below I extract the dimensions of the matrix from the sparse data structure. Understanding why these dimensions make sense is the first step to this exercise.

In [ ]:
import numpy as np

def dense_to_coo(dense_mat: np.array) -> dict:
  coo = {'rows':[], 'cols':[], 'data':[]} #3 lists: a list of rows, a list of cols, and a list of data

  for i in range(dense_mat.shape[0]):
    for j in range(dense_mat.shape[1]) :
      if dense_mat[i,j] != 0:
        coo['rows'].append(i)
        coo['cols'].append(j)
        coo['data'].append(dense_mat[i,j])

  return coo

test_dense_to_coo = dense_to_coo(A) #A is dense
test_dense_to_coo #test_dense_to_coo is coo


def dense_to_csr(dense_mat: np.array) -> dict:
  csr = {'cols':[], 'data':[], 'indptr':[]} #indices is cols go to scipy.sparse_csr_array

  csr['indptr'].append(0)
  for i in range(dense_mat.shape[0]):
    row_data_count = 0
    for j in range(dense_mat.shape[1]):
      if dense_mat[i,j] != 0:
        csr['data'].append(dense_mat[i,j])
        csr['cols'].append(j)
        row_data_count += 1
    row_start = csr['indptr'][-1]
    csr['indptr'].append(row_start + row_data_count)

  return csr

test_dense_to_csr = dense_to_csr(A) #A is dense
test_dense_to_csr


def coo_to_dense(coo_mat: dict) -> np.array:
  num_rows = max(coo_mat['rows']) + 1
  num_cols = max(coo_mat['cols']) + 1
  dense_mat = np.zeros((num_rows, num_cols))


  #with zip: for i, j, value in zip(coo_mat['rows'], coo_mat['cols'], coo_mat['data']):
    #with zip: dense_mat[i, j] = value

  #without zip:
  for i in range(len(coo_mat['rows'])):
    dense_mat[coo_mat['rows'][i], coo_mat['cols'][i]] = coo_mat['data'][i]
  return dense_mat


test_coo_to_dense = coo_to_dense(test_dense_to_coo) #test_dense_to_coo is coo
test_coo_to_dense


def csr_to_dense(csr_mat: dict) -> np.array:
  num_rows = len(csr_mat['indptr']) - 1
  num_cols = max(csr_mat['cols']) + 1
  dense_mat = np.zeros((num_rows, num_cols))

  for row_index in range(num_rows):
    row_start = csr_mat['indptr'][row_index]
    row_end = csr_mat['indptr'][row_index + 1]
    row_data = csr_mat['data'][row_start:row_end]
    #print(f'{row_index} : {row_data}')
    col_indices = csr_mat['cols'][row_start:row_end]
    for val, col_index in zip(row_data, col_indices):
      dense_mat[row_index, col_index] = val

  return dense_mat

test_csr_to_dense = csr_to_dense(test_dense_to_csr) #test_dense_to_csr is csr
test_csr_to_dense

array([[1., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 1., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0.]])

### Checking Exercise 2.3

Converting from dense to sparse back to dense should have no change.

In [ ]:
from numpy.linalg import norm

#### dense -> coo -> dense

In [ ]:
coo = dense_to_coo(A)
reconstruction = coo_to_dense(coo)
if norm(A) > 0.0 and norm(A - reconstruction) < 1e-5:
  print('Good job!')
else:
  print('Not quite')
print(A)
print(coo)
print(reconstruction)


Good job!
[[1. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0.]]
{'rows': [0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5], 'cols': [0, 1, 6, 2, 7, 1, 2, 4, 5, 0, 2, 5, 1, 3, 3, 6], 'data': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]}
[[1. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0.]]



#### dense -> csr -> dense

In [ ]:
csr = dense_to_csr(A)
reconstruction = csr_to_dense(csr)
if norm(A) > 0.0 and norm(A - reconstruction) < 1e-5:
  print('Good job!')
else:
  print('Not quite')
print(A)
print(csr)
print(reconstruction)

Good job!
[[1. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0.]]
{'cols': [0, 1, 6, 2, 7, 1, 2, 4, 5, 0, 2, 5, 1, 3, 3, 6], 'data': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], 'indptr': [0, 3, 5, 9, 12, 14, 16]}
[[1. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0.]]


#### We can also check using `scipy`

Here I convert the dense matrix to the sparse object format provided by `scipy` and access the attributes to create the `dict` version that you built in the previous exercise. Make sure the `dicts` produced by your code matches these.

In [ ]:
from scipy import sparse

print('coo:')
coo = sparse.coo_matrix(A)
coo_dict = {'data': coo.data, 'rows': coo.row, 'cols': coo.col}
print(coo_dict)
print(coo)

print('\ncsr:')
csr = sparse.csr_matrix(A)
csr_dict = {'data': csr.data, 'cols': csr.indices, 'indptr': csr.indptr}
print(csr_dict)
print(csr)

coo:
{'data': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 'rows': array([0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5], dtype=int32), 'cols': array([0, 1, 6, 2, 7, 1, 2, 4, 5, 0, 2, 5, 1, 3, 3, 6], dtype=int32)}
  (0, 0)	1.0
  (0, 1)	1.0
  (0, 6)	1.0
  (1, 2)	1.0
  (1, 7)	1.0
  (2, 1)	1.0
  (2, 2)	1.0
  (2, 4)	1.0
  (2, 5)	1.0
  (3, 0)	1.0
  (3, 2)	1.0
  (3, 5)	1.0
  (4, 1)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (5, 6)	1.0

csr:
{'data': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), 'cols': array([0, 1, 6, 2, 7, 1, 2, 4, 5, 0, 2, 5, 1, 3, 3, 6], dtype=int32), 'indptr': array([ 0,  3,  5,  9, 12, 14, 16], dtype=int32)}
  (0, 0)	1.0
  (0, 1)	1.0
  (0, 6)	1.0
  (1, 2)	1.0
  (1, 7)	1.0
  (2, 1)	1.0
  (2, 2)	1.0
  (2, 4)	1.0
  (2, 5)	1.0
  (3, 0)	1.0
  (3, 2)	1.0
  (3, 5)	1.0
  (4, 1)	1.0
  (4, 3)	1.0
  (5, 3)	1.0
  (5, 6)	1.0


## Homework 2

In Homework 1 you were tasked with decomposing a dense system into $A=LU$ and then solving a system $Ax=b$ for $x$ using this decomposition. With sparse matrices, the $LU$ decomposition is rarely used because it likely destroys the sparsity unless you can use knowledge about the structure to select your pivot points.

For this homework, we will load in one of the symmetric matrix martket sparse systems and just throw away the bottom half. The task of solving $Ax=b$ is the same, but never convert $A$ to the dense format. Do all of your work with the `CSR`.

In [ ]:
import numpy as np
from google.colab import drive
from scipy.io import mmread
from scipy import sparse
from scipy.sparse.linalg import spsolve_triangular
from numpy.linalg import norm

drive.mount('/content/drive')
# NOTE: change this to the folder in your drive with the data
folder = 'drive/MyDrive/matrices'

Mounted at /content/drive


In [ ]:
#back substitution using dense triu matrix
coo = mmread(f'{folder}/bcsstk25.mtx')

csr = sparse.triu(coo, format='csr') #just doing back sub for triu
b = np.ones(csr.shape[0])

print(coo)
print(csr)
print(b)

#back substitution from HW#1

#find  x  with upper triangular solve:  Ux=v
#equation used: Xn-1 = (Bn-1 - Un-1nXn) / Un-1n-1
# which turns into: X1 = (B1 - sum(with n and j=2 (U1jXj))) / U11

n = coo.shape[0]
x_solutions = np.zeros(n)
csrRowPointers = csr.indptr
csrData = csr.data
csrIndices = csr.indices

print("csrRowPointers:", csrRowPointers)
print("csrIndices:", csrIndices)
print("csrData:", csrData)

numCols = csr.get_shape()[1]
numRows = csr.get_shape()[0]
print("numCols:", numCols)
print("numRows:", numRows)
print("\n n aka length of rows:",n)

for row_index in range(numRows-1, -1, -1):

  Bn = b[row_index]

  row_start = csrRowPointers[row_index]
  row_end = csrRowPointers[row_index + 1]
  row_data = csrData[row_start:row_end]
  col_indices = csrIndices[row_start:row_end]

  for val, col_index in zip(row_data, col_indices):
    Bn -= csr[row_index,col_index] * x_solutions[col_index]

    x_solutions[row_index] = Bn / csr[row_index,row_index]

for x_solution_number in range(len(x_solutions)):
    print("\n x", x_solution_number + 1, ":", x_solutions[x_solution_number])



Streaming output truncated to the last 5000 lines.

 x 12940 : 1.346069761915909e-07

 x 12941 : 9.114069659215383e-07

 x 12942 : 9.117112355527732e-09

 x 12943 : 1.9775441581305194e-09

 x 12944 : -1.2238608906629655e-10

 x 12945 : 1.8705060008507298e-08

 x 12946 : 6.358670463904304e-08

 x 12947 : 1.194378796957549e-07

 x 12948 : 5.073619229360117e-10

 x 12949 : 8.702749549844043e-11

 x 12950 : -7.873463618166259e-10

 x 12951 : 3.73809281392006e-08

 x 12952 : 4.5010409775445705e-08

 x 12953 : 8.68327052338658e-08

 x 12954 : 2.0763225868358375e-10

 x 12955 : 5.873961666957622e-11

 x 12956 : 9.215880368235394e-10

 x 12957 : 7.1572494723542005e-09

 x 12958 : 8.427299981928818e-08

 x 12959 : 5.534535501440546e-07

 x 12960 : 1.4028127683203117e-09

 x 12961 : -2.917054661804141e-09

 x 12962 : 2.4157607832284723e-10

 x 12963 : 2.9291329093827265e-08

 x 12964 : 1.1767904948140966e-07

 x 12965 : 1.432688716135693e-07

 x 12966 : 6.344542062682732e-10

 x 12967 : 1.938399

In [ ]:
def solve(A: sparse.csr, b: np.array) -> np.array:
  x = np.zeros(b.shape)

  return x

#x = solve(csr, b)
correct_x = spsolve_triangular(csr, b, lower=False, unit_diagonal=False)

if norm(x_solutions - correct_x) < 1e-6:
  print('Nice work')
else:
  print('Maybe next time')

Nice work
